name: Handle pushes to PRs
run-name: Check and validate commits pushed to a PR

on:
  # GitGitGadget's GitHub App is expected to trigger this on `pull_request` events
  # that have the `action` set to `opened` or `synchronize`
  workflow_dispatch:
    inputs:
      pr-url:
        description: 'URL of the PR to handle'
        required: true

env:
  PR_URL: ${{ inputs.pr-url }}

concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr-url }}

jobs:
  handle-pr-push:
    runs-on: ubuntu-latest
    if: vars.CONFIG != ''

    steps:
    - uses: actions/create-github-app-token@v1
      id: gitgitgadget-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GITHUB_APP_PRIVATE_KEY }}
        owner: gitgitgadget
        repositories: git
    - uses: actions/create-github-app-token@v1
      id: git-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
        owner: git
        repositories: git
    - uses: actions/create-github-app-token@v1
      id: dscho-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
        owner: dscho
        repositories: git
    - name: create a check run
      id: create-check-run
      run: |
        title="Handle PR push"
        summary="Handling new commits in $PR_URL"
        details_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        text="This handles $PR_URL, see $details_url for details."
        echo "title=$title" >> $GITHUB_OUTPUT
        echo "summary=$summary" >> $GITHUB_OUTPUT
        echo "text=$text" >> $GITHUB_OUTPUT

        PR_NUMBER="${PR_URL##*/}" # skip the prefix before the PR number
        PR_REPO="${PR_URL%/pull/$PR_NUMBER*}" # skip the suffix including the PR number
        PR_REPO="${PR_REPO#https://*/}"

        export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        eval "$(gh api repos/$PR_REPO/pulls/$PR_NUMBER \
          --jq '"head_sha=\(.head.sha) && repo=\(.base.repo.full_name)"')"
        echo "head_sha=$head_sha" >> $GITHUB_OUTPUT
        echo "repo=$repo" >> $GITHUB_OUTPUT

        export GH_TOKEN="$(case "$repo" in
          gitgitgadget/git) echo "${{ steps.gitgitgadget-git-token.outputs.token }}";;
          git/git) echo "${{ steps.git-git-token.outputs.token }}";;
          dscho/git) echo "${{ steps.dscho-git-token.outputs.token }}";;
          *) echo "${{ secrets.GITHUB_TOKEN }}";;
          esac
        )"
        eval "$(gh api repos/$repo/check-runs -X POST \
          -f name='handle_pr_push' \
          -f head_sha="$head_sha" \
          -f status='in_progress' \
          -f details_url="$details_url" \
          -f "output[title]=$title" \
          -f "output[summary]=$summary" \
          -f "output[text]=$text" \
          --jq '"check_run_id=\(.id)"')"
        echo "check_run_id=$check_run_id" >> $GITHUB_OUTPUT
    - uses: gitgitgadget/gitgitgadget/handle-pr-push@v1
      with:
        config: ${{ vars.CONFIG }}
        pr-repo-token: ${{ steps.gitgitgadget-git-token.outputs.token }}
        upstream-repo-token: ${{ steps.git-git-token.outputs.token }}
        test-repo-token: ${{ steps.dscho-git-token.outputs.token }}
        pr-url: ${{ env.PR_URL }}
    - name: update the check run
      if: always() && steps.create-check-run.outputs.check_run_id != ''
      run: |
        export GH_TOKEN="$(case "${{ steps.create-check-run.outputs.repo }}" in
          gitgitgadget/git) echo "${{ steps.gitgitgadget-git-token.outputs.token }}";;
          git/git) echo "${{ steps.git-git-token.outputs.token }}";;
          dscho/git) echo "${{ steps.dscho-git-token.outputs.token }}";;
          *) echo "${{ secrets.GITHUB_TOKEN }}";;
          esac
        )"
        gh api repos/${{ steps.create-check-run.outputs.repo }}/check-runs/${{ steps.create-check-run.outputs.check_run_id }} \
          -X PATCH \
          -f status='completed' \
          -f conclusion='${{ job.status }}' \
          -f 'output[title]=${{ steps.create-check-run.outputs.title }}' \
          -f 'output[summary]=${{ steps.create-check-run.outputs.summary }}' \
          -f 'output[text]=${{ steps.create-check-run.outputs.text }}'
